CREATE TABLE `SG_ACCOUNT_TEST`
(
    SAT_ID    int(30) PRIMARY KEY,
    SAT_NAME  varchar(20),
    SAT_VALUE DECIMAL(10, 2)
);

INSERT INTO SG_ACCOUNT_TEST (SAT_ID, SAT_NAME, SAT_VALUE)
VALUES (1, '小李', 3000);
INSERT INTO SG_ACCOUNT_TEST (SAT_ID, SAT_NAME, SAT_VALUE)
VALUES (2, '小王', 3000);