CREATE TABLE `SG_CLASS_TEACHER_REL`
(
    SCTR_CID int(10) COMMENT '班级ID',
    SCTR_TID int(10) COMMENT '教师ID',
    PRIMARY KEY (SCTR_CID, SCTR_TID),
    CONSTRAINT FK_REL_CLASS_REL FOREIGN KEY (SCTR_CID) REFERENCES SG_CLASS_INF (SCI_ID),
    CONSTRAINT FK_REL_TEACHER_REL FOREIGN KEY (SCTR_TID) REFERENCES SG_TEACHER_INF (STI_ID)
);

INSERT INTO SG_CLASS_TEACHER_REL (SCTR_CID, SCTR_TID)
VALUES (10001, 1000001);
INSERT INTO SG_CLASS_TEACHER_REL (SCTR_CID, SCTR_TID)
VALUES (10001, 1000002);
INSERT INTO SG_CLASS_TEACHER_REL (SCTR_CID, SCTR_TID)
VALUES (10002, 1000001);
INSERT INTO SG_CLASS_TEACHER_REL (SCTR_CID, SCTR_TID)
VALUES (10002, 1000002);
INSERT INTO SG_CLASS_TEACHER_REL (SCTR_CID, SCTR_TID)
VALUES (10003, 1000003);