CREATE TABLE `SGP_USER_ROLE_REL`
(
    SURR_UID VARCHAR(10) COMMENT '用户ID',
    SURR_RID VARCHAR(10) COMMENT '角色ID',
    PRIMARY KEY (SURR_UID, SURR_RID),
    CONSTRAINT FK_REL_USER_SGPRU FOREIGN KEY (SURR_UID) REFERENCES SGP_USER (SU_ID),
    CONSTRAINT FK_REL_ROLE_SGPRU FOREIGN KEY (SURR_RID) REFERENCES SGP_ROLE (SR_ID)
);
INSERT INTO `SGP_USER_ROLE_REL` (SURR_UID, SURR_RID)
VALUES ('10001', '1001');