CREATE TABLE `SGP_PERMISSION`
(
    SP_ID       VARCHAR(10) PRIMARY KEY COMMENT 'ID',
    SP_NAME     VARCHAR(64) COMMENT '名称',
    SP_NICKNAME VARCHAR(64) COMMENT '角色别名',
    SP_URL      VARCHAR(512) COMMENT 'URL',
    SP_DESCRIBE VARCHAR(64) COMMENT '角色描述'
);
INSERT INTO `SGP_PERMISSION` (SP_ID, SP_NAME, SP_NICKNAME, SP_URL, SP_DESCRIBE)
VALUES ('1001', 'USER', 'USER', '','普通角色');