CREATE TABLE `SG_APP_USER_HIBERNATE_REL`(
	SAUHR_AID int(10),--APP ID
	SAUHR_UID int(10),--用户ID
	PRIMARY KEY(SAUHR_AID,SAUHR_UID),
	CONSTRAINT FK_REL_APP_REL FOREIGN KEY(SAUHR_AID) REFERENCES SG_APP_HIBERNATE_INF(SAHI_ID),
	CONSTRAINT FK_REL_USER_REL FOREIGN KEY(SAUHR_UID) REFERENCES SG_USER_HIBERNATE_INF(SUHI_ID)
);