CREATE TABLE `SG_CLASS_INF`
(
    SCI_ID       int(10) PRIMARY KEY,-- 班级ID
    SCI_NAME     varchar(20),-- 班级名称
    SCI_DESCRIBE varchar(100)-- 班级介绍
);
INSERT INTO `SG_CLASS_INF` (SCI_ID, SCI_NAME, SCI_DESCRIBE)
VALUES (10001, '高一一班', '高一重点班');
INSERT INTO `SG_CLASS_INF` (SCI_ID, SCI_NAME, SCI_DESCRIBE)
VALUES (10002, '高一二班', '高一重点班');
INSERT INTO `SG_CLASS_INF` (SCI_ID, SCI_NAME, SCI_DESCRIBE)
VALUES (10003, '高一三班', '高一普通班');