CREATE TABLE `SG_USER_INFO`
(
    SUI_ID       varchar(10) PRIMARY KEY,-- 用户号，首位：（0：管理员用户，1：普通用户）
    SUI_NAME     varchar(64),-- 用户名
    SUI_NICKNAME VARCHAR(64),-- 别名
    SUI_MOBILE   varchar(11),-- 手机
    SUI_EMAIL    VARCHAR(128),-- 电子邮箱
    SUI_AGE      int(3),-- 用户年龄
    SUI_STT      varchar(2),-- 用户状态（0：待激活，1：正常，X：已注销）
    SUI_CREADATE date,-- 创建日期
    SUI_MODIDATE date-- 修改日期
);
INSERT INTO `SG_USER_INFO` (SUI_ID, SUI_NAME, SUI_EMAIL, SUI_AGE, SUI_STT, SUI_CREADATE, SUI_MODIDATE)
VALUES ('0000000001', 'ROOT', 'gaoyx1469@163.com', 18, '1', NOW(), NOW());
INSERT INTO `SG_USER_INFO` (SUI_ID, SUI_NAME, SUI_MOBILE, SUI_AGE, SUI_STT, SUI_CREADATE, SUI_MODIDATE)
VALUES ('0000000002', '高级管理员01', '17600112233', 18, '1', CURDATE(), CURDATE());
INSERT INTO `SG_USER_INFO` (SUI_ID, SUI_NAME, SUI_MOBILE, SUI_AGE, SUI_STT, SUI_CREADATE, SUI_MODIDATE)
VALUES ('0000000003', '高级管理员02', '17600112234', 18, '0', CURRENT_DATE(), CURRENT_DATE());
INSERT INTO `SG_USER_INFO` (SUI_ID, SUI_NAME, SUI_NICKNAME, SUI_AGE, SUI_STT, SUI_CREADATE, SUI_MODIDATE)
VALUES ('1000000001', '豆豆', 'doudou', 18, '1', CURRENT_DATE(), CURRENT_DATE());