CREATE TABLE `SGP_USER`
(
    SU_ID       VARCHAR(10) PRIMARY KEY COMMENT '用户号',
    SU_NAME     VARCHAR(64) COMMENT '用户姓名',
    SU_NICKNAME VARCHAR(64) COMMENT '用户昵称',
    SU_MOBILE   VARCHAR(11) COMMENT '手机号',
    SU_EMAIL    VARCHAR(128) COMMENT '电子邮箱',
    SU_BIRTHDAY VARCHAR(10) COMMENT '生日',
    SU_PASSWORD VARCHAR(512) COMMENT '用户密码',
    SU_STT      VARCHAR(2) COMMENT '用户状态（0：待激活，1：正常，X：已注销）',
    SU_CREADATE DATE COMMENT '用户创建日期',
    SU_MODIDATE DATE COMMENT '用户信息修改日期'
);
INSERT INTO `SGP_USER` (SU_ID, SU_NAME, SU_NICKNAME, SU_MOBILE, SU_EMAIL, SU_BIRTHDAY, SU_PASSWORD, SU_STT, SU_CREADATE,
                        SU_MODIDATE)
VALUES ('10001', '豆豆', '二豆', '13312345678', 'doudou@163.com', '20000101', '', '1', NOW(), NOW());