CREATE TABLE `SGP_ROLE`
(
    SR_ID       VARCHAR(10) PRIMARY KEY COMMENT '角色号',
    SR_NAME     VARCHAR(64) COMMENT '角色名称',
    SR_NICKNAME VARCHAR(64) COMMENT '角色别名',
    SR_DESCRIBE VARCHAR(64) COMMENT '角色描述'
);
INSERT INTO `SGP_ROLE` (SR_ID, SR_NAME, SR_NICKNAME, SR_DESCRIBE)
VALUES ('1001', 'USER', 'USER', '普通角色');